### ISSUE TITLE
Server Implementation Example 404

### ISSUE THREAD

**Issue by Joeao** [rwth-acis/yjs#10]
Hi there,

Yatta looks awesome. I started to implement it today after spending 6 1/2 hours trying to use an alternative solution, before finding that it's seemingly incompatible with my other dependencies.

I'm looking to use my own NodeJS server to store rooms, for the sake of having control over all rooms and not needing to depend on another service, however the example in the tutorial has a dead link: https://github.com/DadaMonad/meme-together/blob/master/server.js. I've looked through the repository and can't find any existence of the file even in the past.

Thanks!
Joe

**Comment by DadaMonad** [comment]
Hey Joe, nice to hear from you!

I'm sorry for that, I did not yet commit the server.js. You can use this one for the moment:

```
var Yatta = require('../yjs/build/node/y.js');
XMPPConnector = require('../y-connectors/build/node/index').XMPP;

var connector = new XMPPConnector("random-hash", {
  host: "yatta.ninja", // when you work on the server, you must specify the host
});

connector.debug = true; // if you want to see the debug logs

var y = new Yatta(connector);
var feed = y.val("feed",[],"mutable").val("feed");

/*
 Do not allow a feed size greater that 10
*/

var feed_size = 10;

feed.observe(function(){
  // whenever something changed, check if the feed size exceeds 10
  var length = feed.val().length;
  if(length > feed_size){
    feed.delete(feed_size,length-feed_size)
  }
})
console.log("listening!")

```

Best,
Kevin

**Comment by Joeao** [comment]
Hi Kevin,
That looks much easier than I'd thought. I'll attempt to use it tomorrow and will get back to you on how it goes.

My goal is to have the framework implemented on my project by Monday. I'll continue on it each day until then and will let you know how it goes. I'd love to help out with the project in some way, whether that be just feedback, or helping to write some documentation or something. It's an exciting project and the work you've put into it so far is brilliant. Keep it up!

**Comment by episodeyang** [comment]
Hey guys, this is great, because I wanted to use my own node server to
store rooms too.

**Comment by nicolaescu** [comment]
Hi guys,
We are very happy that you like the framework! 
Would be great if you can give us any feedback! We would also like to know if possible some details about your projects (related to the usability of yjs) – links would also do the trick. The main purpose behind yjs is to enable and foster real-time collaboration for professional communities, so we are interested in any stories about how it is currently being used..

**Comment by episodeyang** [comment]
Oh cool! I already talked to Kevin!

How many people are on the team now?

here is what I am trying to build: www.escherpad.com

Ge

**Comment by DadaMonad** [comment]
We had to rename everything from Yatta -> yjs. So don't get confused. I updated the [website](https://dadamonad.github.io/yjs/) accordingly. The `server.js` file is commited now.

@episodeyang It's Petru and me for now.

**Comment by petermilan** [comment]
Hello there, where can I find the example server? can not find it in y-js repository

**Comment by DadaMonad** [comment]
Hi Peter,
don't geht confused, yjs dies not need a Server in order to work. But here is an example how you can use it with nodejs:https://github.com/y-js/meme-together/blob/master/server.js

**Comment by Joeao** [comment]
Hey guys,
The "How to create your own connector" blog post may also be useful. However if it finished with example code of both client and server, it would become a much more valuable resource as it would cover every necessary detail. https://dadamonad.github.io//yjs/connector/Howto-create-your-own-Connector.html

**Comment by cphyc** [comment]
@Joeao, you're right. I made an implementation of yjs in http://hubl.in. I'm sending to the maintainer of the repo to serve as an example.
